In [6]:
import numpy as np
import matplotlib as plt

In [2]:
def plot_vector2d(vector2d, origin=[0, 0], **options):
    return plt.arrow(origin[0], origin[1], vector2d[0], vector2d[1],
              head_width=0.2, head_length=0.3, length_includes_head=True,
              **options)

In [4]:
T = np.array([[1,0], [0, -1]])

In [7]:
arr = np.array([4,2])
plot_vector2d(arr, color='r')
plot_vector2d(T @ arr, color='g')

plt.axis([0,10,0,10]) # rentang axis sumbu x dan y
plt.grid()
plt.show()
plot_vector2d(arr, color='r')

AttributeError: module 'matplotlib' has no attribute 'arrow'

In [9]:
A = np.array([
    [1,2],
    [2,4]
])

In [11]:
eig_val, eig_vec = np.linalg.eig(A)

In [12]:
eig_val

array([0., 5.])

In [13]:
eig_vec

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [15]:
v = np.array([1,2]) / np.sqrt(5)

In [16]:
# A x = lambda x
hasil = A @ v
hasil / 5

array([0.4472136 , 0.89442719])

In [17]:
np.diag(eig_val)

array([[0., 0.],
       [0., 5.]])

In [18]:
np.linalg.inv(eig_vec)

array([[-0.89442719,  0.4472136 ],
       [-0.4472136 , -0.89442719]])

In [20]:
reconstruct = eig_vec @ np.diag(eig_val) @ np.linalg.inv(eig_vec)
reconstruct

array([[1., 2.],
       [2., 4.]])

Implementasi - Social Media Network

In [23]:
N = np.array([[0,1/4,0,1/2,0,0],
[0, 0, 0, 0, 0, 0],
[1/2, 1/4, 0, 0, 0, 1/2],
[1/2, 1/4, 0, 0, 0,  1/2],
[0, 1/4, 0, 1/2, 0, 0],
[0, 0, 0, 0, 0, 0]
])

In [24]:
N

array([[0.  , 0.25, 0.  , 0.5 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.5 , 0.25, 0.  , 0.  , 0.  , 0.5 ],
       [0.5 , 0.25, 0.  , 0.  , 0.  , 0.5 ],
       [0.  , 0.25, 0.  , 0.5 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [25]:
eig_val, eig_vec = np.linalg.eig(N)

In [26]:
eig_val

array([ 0. ,  0. ,  0.5, -0.5,  0. ,  0. ])

In [27]:
eig_vec

array([[ 0.00000000e+000,  0.00000000e+000,  5.00000000e-001,
        -5.00000000e-001, -2.16623325e-276, -2.34960985e-276],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  4.33246650e-276,  0.00000000e+000],
       [ 0.00000000e+000,  1.00000000e+000,  5.00000000e-001,
         5.00000000e-001,  6.00000000e-001,  2.16930458e-001],
       [ 0.00000000e+000,  0.00000000e+000,  5.00000000e-001,
         5.00000000e-001, -2.16623325e-276,  1.17386593e-291],
       [ 1.00000000e+000,  0.00000000e+000,  5.00000000e-001,
        -5.00000000e-001, -8.00000000e-001, -9.76187060e-001],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  2.34960985e-276]])

In [28]:
np.argmax(eig_val)

2

In [35]:
np.argmax(eig_vec[2])

1

Agen B yang berada di index eigen vector ke-1, merupakan agen dengan ranking terbesar diantara yang lainnya berdasarkan perhitungan page rank eigen.