**MATRIX**

In [1]:
import numpy as np

In [2]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [3]:
A.shape

(3, 3)

In [4]:
A[0,:]

array([1, 2, 3])

In [5]:
A[:, 2]

array([3, 6, 9])

Matrix Diagonal

In [6]:
np.diag(A)

array([1, 5, 9])

In [7]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

Matriks identitas

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
A @ np.eye(3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Operasi Aritmatika**

In [11]:
B = np.array([[2,1,1],
            [1,0,3],
            [0,1,2]
])
B

array([[2, 1, 1],
       [1, 0, 3],
       [0, 1, 2]])

Penjumlahan

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
10 + A

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [14]:
A + B

array([[ 3,  3,  4],
       [ 5,  5,  9],
       [ 7,  9, 11]])

In [15]:
np.diag(np.diag(A) + np.diag(B))

array([[ 3,  0,  0],
       [ 0,  5,  0],
       [ 0,  0, 11]])

Pengurangan

In [16]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
B

array([[2, 1, 1],
       [1, 0, 3],
       [0, 1, 2]])

In [18]:
A - B

array([[-1,  1,  2],
       [ 3,  5,  3],
       [ 7,  7,  7]])

In [19]:
np.diag(np.diag(A) - np.diag(B))

array([[-1,  0,  0],
       [ 0,  5,  0],
       [ 0,  0,  7]])

Pembagian

In [20]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
B

array([[2, 1, 1],
       [1, 0, 3],
       [0, 1, 2]])

In [22]:
A / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [23]:
np.diag(np.diag(A) / np.diag(B))

C:\Users\Fahmi Hamzah\AppData\Local\Temp\ipykernel_17760\1373775744.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.diag(np.diag(A) / np.diag(B))


array([[0.5, 0. , 0. ],
       [0. , inf, 0. ],
       [0. , 0. , 4.5]])

Perkalian

Scalar

In [24]:
10 * A

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

Hadamard (Element-wise multiplication)

In [25]:
A * B

array([[ 2,  2,  3],
       [ 4,  0, 18],
       [ 0,  8, 18]])

MATRIX MUTLTIPLICATION (Dot)

In [26]:
F = np.array([[2,1,0],
            [0,2,2],
            [1,0,1],
            [3,0,1]
])

In [27]:
G = np.array([[1,0],
            [0,4],
            [5,2]
])

In [28]:
F @ G

array([[ 2,  4],
       [10, 12],
       [ 6,  2],
       [ 8,  2]])

**Transpose**

In [29]:
G.T

array([[1, 0, 5],
       [0, 4, 2]])

**Inverse**

In [30]:
B

array([[2, 1, 1],
       [1, 0, 3],
       [0, 1, 2]])

In [31]:
B_inv = np.linalg.inv(B)

In [32]:
B @ B_inv

array([[ 1.00000000e+00,  0.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [33]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.linalg.inv(A)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [35]:
S = np.array([[2,5,1],
[4,10,2],
[3,1,1]
])

In [36]:
np.linalg.inv(S)

LinAlgError: Singular matrix

Determinant

In [37]:
K = np.array([
    [2,1],
    [2,8]
])

In [38]:
K

array([[2, 1],
       [2, 8]])

In [39]:
np.linalg.det(K)

13.999999999999996

In [40]:
J = np.array([
    [8, -1],
    [-2, 2]
])
J / 14

array([[ 0.57142857, -0.07142857],
       [-0.14285714,  0.14285714]])

In [41]:
np.linalg.inv(K)

array([[ 0.57142857, -0.07142857],
       [-0.14285714,  0.14285714]])

In [56]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [55]:
np.linalg.inv(A)

array([[-2.81474977e+14,  5.62949953e+14, -2.81474977e+14],
       [ 5.62949953e+14, -1.12589991e+15,  5.62949953e+14],
       [-2.81474977e+14,  5.62949953e+14, -2.81474977e+14]])

Tensor

In [43]:
M1 = np.array([
    [1, 1, 8],
    [2, 5, 1],
])
M2 = np.array([
    [1, 8, 7],
    [2, 0, 0],
])
M3 = np.array([
    [9, 3, 8],
    [2, 3, 12],
])
M4 = np.array([
    [14, 15, 8],
    [2, 7, 1],
])

In [46]:
tensor = np.array([M1, M2, M3, M4])

In [47]:
tensor.shape

(4, 2, 3)