In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = np.array([1, 3, 4])
b = np.array([4, 3, 2])

a+b

array([5, 6, 6])

In [4]:
list1 = [1, 3, 5]
list2 = [3, 4, 7]

list1 + list2

[1, 3, 5, 3, 4, 7]

In [16]:
v = np.array([4, 3])

In [ ]:
plot_vector2d(v, color='r')

Vector Norm

In [5]:
np.linalg.norm(a)

5.0990195135927845

Manhattan Distance

In [ ]:
np.linalr.norm()

Vector Satuan

In [7]:
np.linalg.norm(np.array([4/5, 3/5]))

1.0

In [9]:
np.linalg.norm((a/np.linalg.norm(a)))

1.0

Operasi aritmatika

**Penjumlahan**

In [10]:
print(a, b)

[1 3 4] [4 3 2]


Penjumlahan vektor dengan skalar

In [11]:
a + 10

array([11, 13, 14])

Penjumlahan vektor dengan vektor

In [12]:
a + b

array([5, 6, 6])

**Pengurangan**

In [15]:
print(a, b)

[1 3 4] [4 3 2]


Pengurangan vektor dengan skalar

In [13]:
10 - a

array([9, 7, 6])

Pengurangan vektor dengan vektor

In [14]:
b - a

array([ 3,  0, -2])

**Pembagian**

In [17]:
print(a, b)

[1 3 4] [4 3 2]


Pembagian vektor dengan skalar

In [18]:
15 / a

array([15.  ,  5.  ,  3.75])

Pembagian vektor dengan vektor

In [20]:
a / b

array([0.25, 1.  , 2.  ])

**Perkalian**

In [23]:
print(a, b)

[1 3 4] [4 3 2]


Perkalian vektor dengan skalar "SCALING"

In [21]:
a * 2

array([2, 6, 8])

Perkalian vektor dengan vector --element-wise multiplication

In [24]:
a * b

array([4, 9, 8])

Dot Product

In [25]:
a.dot(b)

21

In [26]:
np.dot(a, b)

21

In [27]:
a @ b

21

#### **Cosine Similarity**

In [28]:
print(a, b)

[1 3 4] [4 3 2]


In [30]:
cos_theta = a @ b / (np.linalg.norm(a) * np.linalg.norm(b))
cos_theta

0.7647748927656913

In [42]:
arr_1 = np.array([4, 0])
arr_2 = np.array([0, 4])

In [43]:
def cos_similarity(arr_1, arr_2):
    cos_theta = arr_1 @ arr_2 / (np.linalg.norm(arr_1) * np.linalg.norm(arr_2))
    return cos_theta

In [44]:
cos_similarity(arr_1, arr_2)


0.0

Contoh kasus

- kalimat 1 = kemarin saya pergi ke rumah kakek saya
- kalimat 2 = kemarin saya pergi ke rumah nenek saya

In [45]:
kal_1 = np.array([1,2,1,1,1,1,0])
kal_2 = np.array([1,2,1,1,1,0,1])

In [46]:
print(kal_1)
print(kal_2)

[1 2 1 1 1 1 0]
[1 2 1 1 1 0 1]


In [47]:
cos_sim = kal_1 @ kal_2 / (np.linalg.norm(kal_1) * np.linalg.norm(kal_2))
cos_sim

0.8888888888888888

In [48]:
np.linalg.norm(kal_1) * np.linalg.norm(kal_2)

9.0

**Contoh lain**

- kalimat 1 = pagi tadi saya test bahasa inggris
- kalimat 2 = malam ini saya di rumah saja

In [51]:
kal_3 = np.array([1,1,1,1,1,1,0,0,0,0,0])
kal_4 = np.array([0,0,1,0,0,0,1,1,1,1,1])

cos_similarity(kal_3, kal_4)

0.16666666666666669

kelemahan
- kal_4 = kucing mengejar tikus
- kal_2 = tikus mengejar kucing

In [53]:
kal_5 = np.array([1, 1, 1])
kal_6 = np.array([1, 1, 1])

In [54]:
cos_similarity(kal_5, kal_6)

1.0000000000000002

In [69]:
array_1 = np.array([8, 0])
array_2 = np.array([0, 7])

cos_sim1 = kal_1 @ kal_2 / (np.linalg.norm(kal_1) * np.linalg.norm(kal_2))
cos_sim1

0.0

0.0